import os

# Read the wizard code from the user prompt and write it to _wizard.txt
# The wizard code is defined here as a raw string

out_path = os.path.join(os.path.dirname(os.path.abspath(__file__)), "_wizard.txt")

with open(out_path, "w", encoding="utf-8") as f:
    f.write("Generated by _gen_wizard.py")

print("Wrote to", out_path)