// ═══════════════════════════════════════════
// SynaBun — Style Guide → W3C design tokens (DTCG 2025.10)
// ═══════════════════════════════════════════
//
// tokens.json in the Design Tokens Community Group format: a token is an object
// with `$value`; groups are objects without one; `$type` is inherited from the
// closest group; an alias is "{group.token}". Value shapes follow the 2025.10
// module: color { colorSpace, components, alpha, hex }, dimension { value, unit },
// duration { value, unit }, cubicBezier [x1, y1, x2, y2], shadow, typography.
// Pure: `generatedAt` is passed in, never read from the clock.

import { parseColor, rgbToHex } from './color.js';
import { isAlias, normalizeStyleGuide, resolveAlias } from './schema.js';
import { fontKeyOf, fontList, parseEasing, parseShadow, themesOf, tidy } from './tokens.js';

export const DTCG_MIME = 'application/design-tokens+json';
export const DTCG_EXTENSION_KEY = 'dev.synabun';

/** A token or group name: DTCG forbids `{`, `}`, `.` and a leading `$`. */
export function dtcgName(value) {
  return String(value).replace(/[{}.]/g, '-').replace(/^\$+/, '') || 'token';
}

/** Any CSS color → the DTCG color value, or null. */
export function dtcgColor(input) {
  const rgb = parseColor(input);
  if (!rgb) return null;
  return {
    colorSpace: 'srgb',
    components: [tidy(rgb.r / 255), tidy(rgb.g / 255), tidy(rgb.b / 255)],
    alpha: tidy(rgb.a ?? 1, 3),
    hex: rgbToHex({ r: rgb.r, g: rgb.g, b: rgb.b }),
  };
}

const dim = (value, unit = 'px') => ({ value: tidy(value), unit });

/** `extension`: what DTCG has no field for (a mobile size, the CSS a shadow was written as), under $extensions["dev.synabun"]. */
function token(value, description, extension = null) {
  const out = { $value: value };
  if (description) out.$description = String(description);
  if (extension && Object.keys(extension).length) out.$extensions = { [DTCG_EXTENSION_KEY]: extension };
  return out;
}

/** A color field of the config as a DTCG value: an alias to the token it names, or the color itself. */
function colorRef(config, raw, theme) {
  if (isAlias(raw)) {
    const hit = resolveAlias(config, raw, { theme });
    if (!hit.ok || hit.kind !== 'color') return null;
    if (hit.group === 'status') return `{color.status.${dtcgName(hit.key)}}`;
    if (hit.group === 'semantic') return `{color.semantic.${theme}.${dtcgName(hit.key)}}`;
    return `{color.${dtcgName(hit.group)}.${dtcgName(hit.key)}}`;
  }
  return dtcgColor(raw);
}

function shadowValue(css) {
  const layers = parseShadow(css);
  if (layers === null) return null;
  if (!layers.length) return { color: dtcgColor('#00000000'), offsetX: dim(0), offsetY: dim(0), blur: dim(0), spread: dim(0) };
  const values = layers.map((layer) => ({
    color: dtcgColor(layer.color) || dtcgColor('#000000'),
    offsetX: dim(layer.offsetX), offsetY: dim(layer.offsetY), blur: dim(layer.blur), spread: dim(layer.spread),
    ...(layer.inset ? { inset: true } : {}),
  }));
  return values.length === 1 ? values[0] : values;
}

/**
 * The guide as a DTCG document (a plain object). Tokens whose CSS cannot be expressed in DTCG
 * (an unreadable shadow, a steps() easing) are left out and listed under
 * `$extensions["dev.synabun"].skipped`.
 */
export function exportDtcg(input, { generatedAt = null } = {}) {
  const config = normalizeStyleGuide(input);
  const themes = themesOf(config);
  const skipped = [];
  const doc = {
    $description: 'Design tokens generated by SynaBun Style Guide. Do not edit by hand.',
    $extensions: { [DTCG_EXTENSION_KEY]: { revision: config.revision, generatedAt: generatedAt || config.updatedAt || null, projectPath: config.projectPath, skipped } },
  };

  // ── color ──
  const color = { $type: 'color' };
  for (const [key, palette] of Object.entries(config.colors.palettes)) {
    const group = palette.usage ? { $description: palette.usage } : {};
    for (const [step, hex] of Object.entries(palette.steps)) group[dtcgName(step)] = token(dtcgColor(hex));
    color[dtcgName(key)] = group;
  }
  color.status = {};
  for (const [key, hex] of Object.entries(config.colors.status)) color.status[dtcgName(key)] = token(dtcgColor(hex));
  color.semantic = {};
  for (const theme of themes) {
    const group = {};
    for (const [role, raw] of Object.entries(config.colors.semantic[theme])) {
      const value = colorRef(config, raw, theme);
      if (value) group[dtcgName(role)] = token(value);
      else skipped.push(`color.semantic.${theme}.${role}`);
    }
    color.semantic[theme] = group;
  }
  doc.color = color;

  // ── typography ──
  const fontFamily = { $type: 'fontFamily' };
  for (const [key, font] of Object.entries(config.typography.fonts)) {
    if (font) fontFamily[key] = token(fontList(font), `${font.source} · weights ${font.weights.join(', ')}`, { source: font.source, weights: font.weights, ...(font.features ? { features: font.features } : {}) });
  }
  doc.fontFamily = fontFamily;
  const typography = { $type: 'typography' };
  const lineHeight = { $type: 'number' };
  for (const [id, style] of Object.entries(config.typography.styles)) {
    typography[dtcgName(id)] = token({
      fontFamily: `{fontFamily.${fontKeyOf(config, style)}}`,
      fontSize: dim(style.size),
      fontWeight: style.weight,
      letterSpacing: dim(style.letterSpacing * style.size),
      lineHeight: style.lineHeight,
    }, style.usage, { ...(style.mobileSize !== style.size ? { mobileSize: style.mobileSize } : {}), ...(style.transform !== 'none' ? { transform: style.transform } : {}) });
    lineHeight[dtcgName(id)] = token(style.lineHeight);
  }
  doc.typography = typography;
  doc.lineHeight = lineHeight;

  // ── dimensions ──
  const dims = (map, describe = null) => {
    const group = { $type: 'dimension' };
    for (const [key, value] of Object.entries(map)) group[dtcgName(key)] = token(dim(value), describe?.(key));
    return group;
  };
  doc.spacing = dims(config.layout.spacing.scale);
  doc.radius = dims(config.shape.radius);
  doc.radiusRole = { $type: 'dimension' };
  for (const [role, key] of Object.entries(config.shape.radiusRoles)) doc.radiusRole[dtcgName(role)] = token(`{radius.${dtcgName(key)}}`);
  doc.breakpoint = dims(config.layout.breakpoints);
  doc.border = dims(config.shape.borders);

  // ── shadow, motion, numbers ──
  const shadow = { $type: 'shadow' };
  for (const [key, level] of Object.entries(config.shape.elevation)) {
    const value = shadowValue(level.shadow);
    if (value) shadow[dtcgName(key)] = token(value, level.usage, { css: level.shadow });
    else skipped.push(`shadow.${key}`);
  }
  doc.shadow = shadow;
  const duration = { $type: 'duration' };
  for (const [key, ms] of Object.entries(config.motion.durations)) duration[dtcgName(key)] = token(dim(ms, 'ms'));
  doc.duration = duration;
  const cubicBezier = { $type: 'cubicBezier' };
  for (const [key, css] of Object.entries(config.motion.easings)) {
    const value = parseEasing(css);
    if (value) cubicBezier[dtcgName(key)] = token(value);
    else skipped.push(`cubicBezier.${key}`);
  }
  doc.cubicBezier = cubicBezier;
  const zIndex = { $type: 'number' };
  for (const [key, value] of Object.entries(config.layout.zIndex)) zIndex[dtcgName(key)] = token(value);
  doc.zIndex = zIndex;
  return doc;
}

/** tokens.json as text. */
export function exportDtcgText(input, options = {}) {
  return `${JSON.stringify(exportDtcg(input, options), null, 2)}\n`;
}

const DTCG_TYPES = new Set(['color', 'dimension', 'fontFamily', 'fontWeight', 'duration', 'cubicBezier', 'number', 'strokeStyle', 'border', 'transition', 'shadow', 'gradient', 'typography']);

/**
 * Every token of a DTCG document with its inherited type: [{ path, type, value, description, alias }].
 * `problems` lists what a validator would refuse: a token without a type, an alias that names nothing,
 * a name with a forbidden character. The importer and the tests both read this.
 */
export function walkDtcg(doc) {
  const tokens = [];
  const problems = [];
  const visit = (node, path, inherited) => {
    if (!node || typeof node !== 'object' || Array.isArray(node)) return;
    const type = typeof node.$type === 'string' ? node.$type : inherited;
    if ('$value' in node) {
      const alias = typeof node.$value === 'string' && /^\{[^{}]+\}$/.test(node.$value) ? node.$value.slice(1, -1) : null;
      const extension = node.$extensions && typeof node.$extensions === 'object' ? node.$extensions[DTCG_EXTENSION_KEY] : null;
      tokens.push({ path, type: type || null, value: node.$value, description: node.$description || '', alias, extension: extension && typeof extension === 'object' ? extension : null });
      return;
    }
    for (const [key, child] of Object.entries(node)) {
      if (key.startsWith('$')) continue;
      if (/[{}.]/.test(key)) problems.push(`${[...path, key].join('.')}: a name may not contain "{", "}" or "."`);
      visit(child, [...path, key], type);
    }
  };
  visit(doc, [], null);
  const byPath = new Map(tokens.map((entry) => [entry.path.join('.'), entry]));
  const typeOf = (entry, depth = 0) => {
    if (entry.type || !entry.alias || depth > 8) return entry.type;
    const target = byPath.get(entry.alias);
    return target ? typeOf(target, depth + 1) : null;
  };
  for (const entry of tokens) {
    const name = entry.path.join('.');
    if (entry.alias && !byPath.has(entry.alias)) problems.push(`${name}: alias {${entry.alias}} names no token`);
    const type = typeOf(entry);
    if (!type) problems.push(`${name}: no $type`);
    else if (!DTCG_TYPES.has(type)) problems.push(`${name}: unknown $type ${type}`);
    entry.type = type;
  }
  return { tokens, problems };
}
