// ═══════════════════════════════════════════
// SynaBun — DESIGN.md renderer
// Pure function shared by the REST endpoint and
// the MCP tool so both paths emit identical output.
// ═══════════════════════════════════════════

const DEFAULT_LOGO_DIR = '.synabun/style-guide';

function esc(s) {
  if (s == null) return '';
  return String(s).replace(/\|/g, '\\|');
}

function fmtScale(scale) {
  if (!scale || typeof scale !== 'object') return '';
  return Object.entries(scale)
    .map(([k, v]) => `${k}: ${v}px`)
    .join(' · ');
}

function fmtSwatchTable(role, shades) {
  if (!shades || typeof shades !== 'object') return '';
  const rows = Object.entries(shades)
    .map(([shade, hex]) => `| ${esc(shade)} | \`${esc(hex)}\` |`)
    .join('\n');
  return `### ${esc(role)}\n\n| Shade | Hex |\n|-------|-----|\n${rows}`;
}

function fmtStatus(status) {
  if (!status || typeof status !== 'object') return '';
  return Object.entries(status)
    .map(([k, v]) => `- **${esc(k)}** — \`${esc(v)}\``)
    .join('\n');
}

function fmtFont(role, font) {
  if (!font) return '';
  const parts = [];
  if (font.family) parts.push(`family: **${esc(font.family)}**`);
  if (Array.isArray(font.weights) && font.weights.length) parts.push(`weights: ${font.weights.join(', ')}`);
  if (font.size != null) parts.push(`size: ${font.size}px`);
  if (font.lineHeight != null) parts.push(`line-height: ${font.lineHeight}`);
  if (font.scale) parts.push(`scale → ${fmtScale(font.scale)}`);
  return `- **${esc(role)}**: ${parts.join(' · ')}`;
}

function fmtRadii(radius) {
  if (!radius) return '';
  return Object.entries(radius)
    .map(([k, v]) => `\`${esc(k)}\` ${v}px`)
    .join(' · ');
}

function fmtSpacing(spacing) {
  if (!Array.isArray(spacing) || spacing.length === 0) return '';
  return spacing.map(v => `${v}px`).join(' / ');
}

function fmtShadows(shadows) {
  if (!shadows) return '';
  return Object.entries(shadows)
    .map(([k, v]) => `- **${esc(k)}** — \`${esc(v)}\``)
    .join('\n');
}

function fmtLogo(logo) {
  if (!logo) return '';
  const lines = [];
  const variants = Array.isArray(logo.variants) ? logo.variants : [];
  if (variants.length) {
    lines.push('### Variants\n');
    for (const v of variants) {
      const label = esc(v.name || v.id || 'Variant');
      const file = v.file ? `${DEFAULT_LOGO_DIR}/${v.file}` : '';
      const bg = v.bg ? ` _(bg: ${esc(v.bg)})_` : '';
      lines.push(file
        ? `- **${label}**${bg} — \`${file}\``
        : `- **${label}**${bg}`);
    }
    lines.push('');
  }
  if (logo.iconLibrary) lines.push(`**Icon library:** ${esc(logo.iconLibrary)}\n`);
  if (logo.imageryNotes) lines.push(`**Imagery direction:**\n\n${logo.imageryNotes}\n`);
  return lines.join('\n');
}

export function renderDesignMd(config) {
  const cfg = config || {};
  const out = [];
  out.push('# Design System');
  out.push('');
  out.push('> Generated by SynaBun Style Guide — do not edit by hand.');
  out.push('> Edit via Neural Interface → Style Guide module. Auto-regenerates on save.');
  if (cfg.updatedAt) out.push(`> Last updated: ${cfg.updatedAt}`);
  out.push('');

  // ── Color Palette ──
  out.push('## Color Palette');
  out.push('');
  const colors = cfg.colors || {};
  const roleOrder = ['primary', 'secondary', 'accent', 'neutral'];
  for (const role of roleOrder) {
    if (colors[role]) {
      out.push(fmtSwatchTable(role.charAt(0).toUpperCase() + role.slice(1), colors[role]));
      out.push('');
    }
  }
  if (colors.status) {
    out.push('### Status');
    out.push('');
    out.push(fmtStatus(colors.status));
    out.push('');
  }

  // ── Typography ──
  const typo = cfg.typography || {};
  out.push('## Typography');
  out.push('');
  if (typo.heading) out.push(fmtFont('Heading', typo.heading));
  if (typo.body)    out.push(fmtFont('Body', typo.body));
  if (typo.mono)    out.push(fmtFont('Mono', typo.mono));
  out.push('');

  // ── Shape & Spacing ──
  const shape = cfg.shape || {};
  out.push('## Shape & Spacing');
  out.push('');
  if (shape.radius)  out.push(`**Radii:** ${fmtRadii(shape.radius)}`);
  if (shape.spacing) out.push(`**Spacing scale:** ${fmtSpacing(shape.spacing)}`);
  if (shape.shadows) {
    out.push('');
    out.push('**Shadows:**');
    out.push('');
    out.push(fmtShadows(shape.shadows));
  }
  out.push('');

  // ── Logo & Imagery ──
  out.push('## Logo & Imagery');
  out.push('');
  out.push(fmtLogo(cfg.logo));

  return out.join('\n').replace(/\n{3,}/g, '\n\n').trim() + '\n';
}

export function defaultStyleGuide(projectPath) {
  return {
    projectPath,
    updatedAt: new Date().toISOString(),
    colors: {
      primary: { 50: '#eff6ff', 100: '#dbeafe', 300: '#93c5fd', 500: '#3b82f6', 900: '#1e3a8a' },
      secondary: { 50: '#f5f3ff', 100: '#ede9fe', 300: '#c4b5fd', 500: '#8b5cf6', 900: '#4c1d95' },
      accent: { 50: '#fefce8', 100: '#fef9c3', 300: '#fde047', 500: '#eab308', 900: '#713f12' },
      neutral: { 50: '#f8fafc', 100: '#f1f5f9', 300: '#cbd5e1', 500: '#64748b', 900: '#0f172a' },
      status: { success: '#22c55e', warning: '#f59e0b', danger: '#ef4444', info: '#0ea5e9' },
    },
    typography: {
      heading: { family: 'Space Grotesk', weights: [600, 700], scale: { h1: 48, h2: 36, h3: 28, h4: 22 } },
      body:    { family: 'Inter', weights: [400, 500], size: 16, lineHeight: 1.5 },
      mono:    { family: 'JetBrains Mono', weights: [400] },
    },
    shape: {
      radius:  { pill: 20, button: 10, card: 8, small: 6 },
      spacing: [4, 8, 12, 16, 24, 32, 48, 64],
      shadows: {
        sm: '0 1px 2px rgba(0,0,0,0.06)',
        md: '0 4px 12px rgba(0,0,0,0.10)',
        lg: '0 12px 32px rgba(0,0,0,0.18)',
      },
    },
    logo: {
      variants: [],
      iconLibrary: 'lucide',
      imageryNotes: '',
    },
  };
}

export const STYLE_GUIDE_LOGO_DIR = DEFAULT_LOGO_DIR;
